### ISSUE TITLE
Dependency conflicts in `requirements.txt` cause unintended package upgrades (e.g., PyTorch)

### ISSUE THREAD

**Issue by EurekaZang** [joyjayng/Bongard-OpenWorld#2]
### **Description**  
After running `pip install -r requirements.txt`, **critical packages (e.g., `torch`) are automatically upgraded to incompatible versions** due to dependency conflicts, leading to environment instability or broken functionality. Although you’ve provided your Conda list, manually aligning versions for numerous packages is error-prone and time-consuming.

### **Steps to Reproduce**  
just follow the README.md
1. Create a new Conda environment:  
   ```bash
    conda create -n bongard-ow python=3.10
    conda activate bongard-ow
    conda install pytorch=1.13 torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
   ```
2. Install dependencies via `requirements.txt`:  
   ```bash
   pip install -r requirements.txt
   ```
3. Verify package versions:  
   ```bash
   pip list | grep torch  # Shows torch 2.6.0 instead of the required 1.13.1
   ```

### **Expected Behavior**  
- `requirements.txt` should pin versions for critical dependencies (e.g., `torch==1.13.1`) to avoid automatic upgrades.  
- The installed environment should remain compatible with the project code.

### **Actual Results**  
- **Version conflicts**: For example, `torch` is upgraded from 1.13.1 to 2.x, causing CUDA incompatibility or API errors.  
- **Error example**:  
  ```python
  ImportError: cannot import name 'xxx' from 'torch' (unknown location)
  ```

### **Proposed Fix**  
1. **Pin dependency versions**:  
   Explicitly specify critical versions in `requirements.txt`, e.g.:  
   ```
   torch==1.13.1+cu117
   torchvision==0.14.1+cu117
   --extra-index-url https://download.pytorch.org/whl/cu117
   ```
2. **Provide multi-environment files**:  
   - Add an `environment.yml` for Conda users to isolate dependency conflicts between pip and Conda.  
 
### **Environment Info**  
- **OS**: Ubuntu 22.04 LTS  
- **Python**: 3.10.12  
- **Package Managers**: pip 25.0 / conda 24.9.2
- **CUDA**: 11.7.99

- I’m happy to test proposed fixes or provide more details!  
- **You can check the log if you like**

[log.txt](https://github.com/user-attachments/files/19343238/log.txt)

**Comment by EurekaZang** [comment]
I created an environment.yml from your conda list, but dependency conflicts prevent installation. 

Here is the `conda list` you provide in issue 1:
[conda_list.txt](https://github.com/user-attachments/files/19409783/conda_list.txt)

Here is the yaml file i create by a script:
```
name: env_bongard
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=1.4.0
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - altair=4.2.2
  - antlr4-python3-runtime=4.9.3
  - anyio=3.6.2
  - appdirs=1.4.4
  - arrow=1.2.3
  - asttokens=2.2.1
  - async-timeout=4.0.2
  - attrs=23.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - black=23.3.0
  - blas=1.0
  - blessed=1.20.0
  - blinker=1.6.2
  - blis=0.7.9
  - braceexpand=0.1.7
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - cachetools=5.3.0
  - catalogue=2.0.8
  - certifi=2023.5.7
  - cffi=1.15.1
  - cfgv=3.3.1
  - chardet=5.2.0
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cloudpickle=2.2.1
  - confection=0.0.4
  - contexttimer=0.3.3
  - contourpy=1.0.7
  - croniter=1.3.14
  - cryptography=39.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cvxpy=1.3.1
  - cycler=0.11.0
  - cymem=2.0.7
  - dateutils=0.6.12
  - decorator=5.1.1
  - decord=0.6.0
  - deepdiff=6.3.0
  - detectron2=0.6
  - distlib=0.3.6
  - distro=1.8.0
  - docker-pycreds=0.4.0
  - ecos=2.0.12
  - einops=0.6.1
  - entrypoints=0.4
  - executing=1.2.0
  - fairscale=0.4.4
  - fastapi=0.88.0
  - ffmpeg=4.3
  - filelock=3.12.0
  - fonttools=4.39.4
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.5.0
  - ftfy=6.1.1
  - fvcore=0.1.5.post20221221
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.31
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.18.0
  - google-auth-oauthlib=1.0.0
  - grpcio=1.54.0
  - h11=0.14.0
  - httpcore=1.0.1
  - httpx=0.25.1
  - huggingface-hub=0.16.4
  - hydra-core=1.3.2
  - identify=2.5.24
  - idna=3.4
  - imageio=2.28.1
  - importlib-metadata=6.6.0
  - inquirer=3.1.3
  - intel-openmp=2023.1.0
  - iopath=0.1.9
  - ipython=8.13.2
  - itsdangerous=2.1.2
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.17.3
  - kaggle=1.5.13
  - kiwisolver=1.4.4
  - lame=3.100
  - langcodes=3.3.0
  - lazy-loader=0.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lightning=2.0.2
  - lightning-cloud=0.5.34
  - lightning-utilities=0.8.0
  - lz4-c=1.9.4
  - markdown=3.4.3
  - markdown-it-py=2.2.0
  - markupsafe=2.1.2
  - matplotlib=3.7.1
  - matplotlib-inline=0.1.6
  - mdurl=0.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - multidict=6.0.4
  - murmurhash=1.0.9
  - mypy-extensions=1.0.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - nodeenv=1.7.0
  - numpy=1.24.3
  - numpy-base=1.24.3
  - oauthlib=3.2.2
  - omegaconf=2.3.0
  - openai=1.1.1
  - opencv-python=4.7.0.72
  - opencv-python-headless=4.5.5.64
  - opendatasets=0.1.22
  - openh264=2.1.1
  - openssl=1.1.1t
  - ordered-set=4.1.0
  - osqp=0.6.2.post9
  - packaging=23.1
  - pandas=2.0.1
  - parso=0.8.3
  - pathspec=0.11.1
  - pathtools=0.1.2
  - pathy=0.10.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=3.5.1
  - plotly=5.14.1
  - portalocker=2.7.0
  - pre-commit=3.3.1
  - preshed=3.0.8
  - prompt-toolkit=3.0.38
  - protobuf=3.20.3
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure-eval=0.2.2
  - pyarrow=12.0.0
  - pyasn1=0.5.0
  - pyasn1-modules=0.3.0
  - pycocoevalcap=1.2
  - pycocotools=2.0.6
  - pycparser=2.21
  - pydantic=1.10.7
  - pydeck=0.8.1b0
  - pygments=2.15.1
  - pyjwt=2.7.0
  - pympler=1.0.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python-editor=1.0.4
  - python-magic=0.4.27
  - python-multipart=0.0.6
  - python-slugify=8.0.1
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-lightning=2.0.2
  - pytorch-mutex=1.0
  - pytz=2023.3
  - pytz-deprecation-shim=0.1.0.post0
  - pywavelets=1.4.1
  - pyyaml=6.0
  - qdldl=0.1.7
  - qpth=0.0.18
  - readchar=4.0.5
  - readline=8.2
  - regex=2023.5.5
  - requests=2.29.0
  - requests-oauthlib=1.3.1
  - rich=13.3.5
  - rsa=4.9
  - safetensors=0.3.2
  - salesforce-lavis=1.0.2
  - scikit-image=0.20.0
  - scipy=1.10.1
  - scs=3.2.3
  - sentencepiece=0.1.99
  - sentry-sdk=1.22.2
  - setproctitle=1.3.2
  - setuptools=67.8.0
  - six=1.16.0
  - smart-open=6.3.0
  - smmap=5.0.0
  - sniffio=1.3.0
  - soupsieve=2.4.1
  - spacy=3.5.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - sqlite=3.41.2
  - srsly=2.4.6
  - stack-data=0.6.2
  - starlette=0.22.0
  - starsessions=1.3.0
  - streamlit=1.22.0
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tenacity=8.2.2
  - tensorboard=2.13.0
  - tensorboard-data-server=0.7.0
  - termcolor=2.3.0
  - text-unidecode=1.3
  - thinc=8.1.10
  - tifffile=2023.4.12
  - timm=0.9.0
  - tk=8.6.12
  - tokenizers=0.13.3
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - torchaudio=0.13.1
  - torchmetrics=0.11.4
  - torchvision=0.14.1
  - tornado=6.3.1
  - tqdm=4.65.0
  - traitlets=5.9.0
  - transformers=4.26.1
  - typer=0.7.0
  - typing_extensions=4.5.0
  - tzdata=2023.3
  - tzlocal=4.3
  - urllib3=1.26.15
  - uvicorn=0.22.0
  - validators=0.20.0
  - virtualenv=20.23.0
  - wandb=0.15.12
  - wasabi=1.1.1
  - watchdog=3.0.0
  - wcwidth=0.2.6
  - webdataset=0.2.48
  - websocket-client=1.5.1
  - websockets=11.0.3
  - werkzeug=2.3.4
  - wheel=0.38.4
  - xz=5.4.2
  - yacs=0.1.8
  - yarl=1.9.2
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.5
```

**Comment by rujiewu** [comment]
I set up the environment from scratch, and the logs can be found [here](https://github.com/user-attachments/files/19415190/logs.txt). Overall, I didn’t encounter any compatibility issues using the latest versions of `torch`, `transformers`, and `timm`.

However, when running `bash fewshot.sh`, I ran into the following error:

```
Traceback (most recent call last):
  File "/home/rujiewu/code/Bongard-OpenWorld/main_bongard.py", line 173, in main
    train_dataset = datasets.make(cfg.train_dataset, **cfg.train_dataset_args)
  File "/home/rujiewu/code/Bongard-OpenWorld/datasets/dataset.py", line 10, in make
    dataset = datasets[name](**kwargs)
TypeError: BongardOWDataset.__init__() missing 1 required positional argument: 'n_shot'
```

To resolve this, I added the missing n_shot: `${bongard_args.n_shot}` field to the YAML config files (`configs/*.yaml`). Here's an example of the updated structure:

```
train_dataset: bongard-ow
train_dataset_args:
  im_root: assets/data/bongard-ow
  problem_file: assets/data/bongard-ow/bongard_ow_train.json
  bbox_file: assets/data/bongard-ow/bbox_data.pkl
  basic_augmentation: False
  extra_augmentation: True
  resize_224: True
  use_clip_stat: False
  n_shot: ${bongard_args.n_shot}    # Added to fix missing 'n_shot' argument

val_dataset: bongard-ow
val_dataset_args:
  im_root: assets/data/bongard-ow
  problem_file: assets/data/bongard-ow/bongard_ow_val.json
  bbox_file: assets/data/bongard-ow/bbox_data.pkl
  basic_augmentation: False
  extra_augmentation: False
  resize_224: True
  use_clip_stat: False
  n_shot: ${bongard_args.n_shot}    # Added to fix missing 'n_shot' argument

test_dataset: bongard-ow
test_dataset_args:
  im_root: assets/data/bongard-ow
  problem_file: assets/data/bongard-ow/bongard_ow_test.json
  bbox_file: assets/data/bongard-ow/bbox_data.pkl
  basic_augmentation: False
  extra_augmentation: False
  resize_224: True
  use_clip_stat: False
  n_shot: ${bongard_args.n_shot}    # Added to fix missing 'n_shot' argument
```

After making these changes, the script executed successfully.
